# Generated by Django 4.1.3 on 2022-12-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_workplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_clients',
        ),
    ]
