# Generated by Django 4.1.3 on 2022-12-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_number_of_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers',
        ),
    ]
