# Generated by Django 4.1.3 on 2022-12-31 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
