# Generated by Django 4.1.3 on 2022-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_question_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_comment',
            field=models.TextField(),
        ),
    ]
