# Generated by Django 4.1.3 on 2022-12-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_question_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
