# Generated by Django 4.1.3 on 2022-12-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_answer_answer_body_alter_answer_answer_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_comment',
            field=models.TextField(default='deafult'),
            preserve_default=False,
        ),
    ]
