# Generated by Django 4.1.3 on 2023-01-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_answer_answer_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('established_year', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('target', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_aim', models.TextField()),
            ],
        ),
    ]
